# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import scan_pb2 as scan__pb2


class VirusScanServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ScanFile = channel.unary_unary(
                '/virusscan.VirusScanService/ScanFile',
                request_serializer=scan__pb2.ScanFileRequest.SerializeToString,
                response_deserializer=scan__pb2.ScanFileResponse.FromString,
                )


class VirusScanServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ScanFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VirusScanServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ScanFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ScanFile,
                    request_deserializer=scan__pb2.ScanFileRequest.FromString,
                    response_serializer=scan__pb2.ScanFileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'virusscan.VirusScanService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VirusScanService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ScanFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/virusscan.VirusScanService/ScanFile',
            scan__pb2.ScanFileRequest.SerializeToString,
            scan__pb2.ScanFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
