# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import dynamo_pb2 as dynamo__pb2


class Dynamo_DBStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckHash = channel.unary_unary(
                '/dynamo_db.Dynamo_DB/CheckHash',
                request_serializer=dynamo__pb2.Request.SerializeToString,
                response_deserializer=dynamo__pb2.Response.FromString,
                )
        self.UpdateHash = channel.unary_unary(
                '/dynamo_db.Dynamo_DB/UpdateHash',
                request_serializer=dynamo__pb2.Request.SerializeToString,
                response_deserializer=dynamo__pb2.Response.FromString,
                )


class Dynamo_DBServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckHash(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateHash(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Dynamo_DBServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckHash': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckHash,
                    request_deserializer=dynamo__pb2.Request.FromString,
                    response_serializer=dynamo__pb2.Response.SerializeToString,
            ),
            'UpdateHash': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateHash,
                    request_deserializer=dynamo__pb2.Request.FromString,
                    response_serializer=dynamo__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dynamo_db.Dynamo_DB', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Dynamo_DB(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckHash(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dynamo_db.Dynamo_DB/CheckHash',
            dynamo__pb2.Request.SerializeToString,
            dynamo__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateHash(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dynamo_db.Dynamo_DB/UpdateHash',
            dynamo__pb2.Request.SerializeToString,
            dynamo__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
