apiVersion: v1
kind: Service
metadata:
  name: safeshare-backend-service
spec:
  selector:
    app: safeshare
    tier: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer