apiVersion: apps/v1
kind: Deployment
metadata:
  name: safeshare-frontend
  labels:
    app: safeshare
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: safeshare
      tier: frontend
  template:
    metadata:
      labels:
        app: safeshare
        tier: frontend
    spec:
      containers:
        - name: safeshare-frontend
          image: amusement3004/safeshare-frontend
          imagePullPolicy: IfNotPresent
          env:  # Add these environment variables
            - name: REACT_APP_API_HOST
              value: safeshare-backend-service  # The name of the backend service
            - name: REACT_APP_API_PORT
              value: "80"  # The port the backend service listens on
          ports:
            - containerPort: 3000