apiVersion: v1
kind: Service
metadata:
  name: safeshare-frontend-service
  labels:
    app: safeshare
    tier: frontend
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 32000  # Optional: This is an example. Kubernetes will assign an available port if you don't specify this.
  selector:
    app: safeshare
    tier: frontend