apiVersion: apps/v1
kind: Deployment
metadata:
  name: safeshare-frontend
  labels:
    app: safeshare
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: safeshare
      tier: frontend
  template:
    metadata:
      labels:
        app: safeshare
        tier: frontend
    spec:
      containers:
        - name: safeshare-frontend
          image: itsmexrando/safeshare-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
