version: '3'

services:
  frontend:
    image: amusement3004/safeshare-frontend:latest
    restart:
      always
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_HOST=http://127.0.0.1:8000
